apiVersion: v1
kind: Service
metadata:
  name: smartskin-backend
  namespace: smartskin
spec:
  type: ClusterIP
  selector:
    app: smartskin-backend
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
