apiVersion: v1
kind: Service
metadata:
  name: smartskin-frontend
  namespace: smartskin
spec:
  type: NodePort
  selector:
    app: smartskin-frontend
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
